# -*- coding: utf-8 -*-
"""D1.MediaEscolar_Camilla

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjtkMvkgfossvnhvBNrKCqok-s5-P6gJ
"""

nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
nota3 = float(input('Digite sua primeira nota: '))

media = (nota1 + nota2 + nota3) / 3

if media >= 7:
    print('Aluno (a) Aprovado')
elif media >= 3:
    print('Aluno (a) Recuperação')
else:
    print('Aluno(a) Reprovado')