# -*- coding: utf-8 -*-
"""D2-Agenda_Camilla

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFQE1SLC0bjzLF5DO2LirLz3aI_rYGvW

Desafio 2-
Implementar um Sistema de Agenda de Tarefas
Um Laço para cadastrar várias Tarefas (while).
Sugestão: Utilizar uma lista e a função append para armazenar os dados
"""

# Agenda de Tarefas
print("=== Sistema de Agenda de Tarefas ===")

# Lista para armazenar as tarefas
tarefas = []

#inicio do loop
while True:
    tarefa = str(input("Digite uma tarefa (ou 'sair' para encerrar): "))

    if tarefa.lower() == "sair": #o "sair" quebra o loop. o lower transforma toda a string em minúsculo, para n ocorrer erro de letra maiúscula
        print(f'Tarefas armazenadas: {tarefas}')
        break  # Sai do loop

    tarefas.append(tarefa)  # Adiciona as tarefas a lista
    print("Tarefa adicionada com sucesso!")

print("\n=== Tarefas cadastradas, fim do programac ===")

#while True : enquanto for verdade, executar o bloco que está abaixo
#append : adicionar algo a lista
#Fazer exercícios para fixar while Trye e append