# -*- coding: utf-8 -*-
"""D3-IMC_Agua-Camilla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTkObQFYgG1eBQgCyTdjmVlQDYNmRBV7

Este exercício em Python tem como objetivo praticar a entrada de dados pelo
usuário, realizar cálculos básicos e apresentar informações formatadas.
O programa solicita ao usuário os seguintes dados:
- Nome - Número do WhatsApp - Peso (em kg) - Altura (em metros)
Com esses dados, o sistema calcula:
O Índice de Massa Corporal (IMC), utilizando a fórmula: IMC = peso /
(altura²).
A ingestão diária de água é recomendada, considerando 35ml de água por kg
de peso corporal.
Por fim, o programa exibe as informações fornecidas e os resultados dos
cálculos, mostrando: - Nome e número do WhatsApp - Peso e altura - Quantidade
de água recomendada por dia
Este exercício integra conceitos básicos de Python como: - Entrada de dados
com input() - Conversão de tipos (string para float) - Operações matemáticas -
Exibição formatada de resultados com print()
"""

# Solicita os dados do usuário
nome = input("Digite seu nome: ")
whatsapp = input("Digite seu número do WhatsApp: ")
peso = float(input("Digite seu peso em kg: "))
altura = float(input("Digite sua altura em metros: "))

# Calcula o IMC
imc = peso / (altura ** 2)

# Calcula a ingestão diária de água recomendada
agua_recomendada = peso * 35

# Exibe as informações e resultados
print("\n--- Informações e Resultados ---")
print(f"Nome: {nome}")
print(f"Número do WhatsApp: {whatsapp}")
print(f"Peso: {peso} kg")
print(f"Altura: {altura} m")
print(f"IMC: {imc:.2f}")
print(f"Ingestão diária de água recomendada: {agua_recomendada:.2f} ml")